version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./server/public:/home/node/app/build
    command: "npm run build"
