version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client/src:/home/node/app/src
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    command: "npm run dev"
    volumes:
      - ./server/src:/home/node/app/src
      - ./server/app.js:/home/node/app/app.js
    ports:
      - 8080:8080
